name: "Warmup Vercel"
on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Request to Vercel
        run: curl -X GET https://online-blade-formatter.vercel.app/
